# Generated by Django 3.2.2 on 2021-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0003_auto_20210512_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetrackrecord',
            name='start_end_records',
            field=models.ManyToManyField(blank=True, null=True, to='timetracker.StartEndTimeRecord'),
        ),
    ]
