# Generated by Django 3.2.2 on 2021-05-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0006_startendtimerecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetrackrecord',
            name='timeinsecond',
        ),
        migrations.AddField(
            model_name='startendtimerecord',
            name='timeinsecond',
            field=models.IntegerField(default=0),
        ),
    ]
